version: '3'

services:
  frontend:
    build:
      context: ./vuetify_server
      dockerfile: Dockerfile.prod
    ports:
      - "4173:4173"
    environment:
      - VUE_APP_API_BASE_URL=http://backend:8000

  backend:
    build:
      context: ./django_server
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env.prod

  postgres:
    image: postgres:latest
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
