# Dockerfile.backend
FROM python:3.8

# Set the working directory to /app
WORKDIR /app

# Copy only necessary files to the working directory
COPY requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project to the working directory
COPY . .
# Copy entrypoint.sh and make it executable
# Copy entrypoint.sh and make it executable
EXPOSE 8000

COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# Specify the command to run on container start
CMD ["/app/entrypoint.sh"]