# Generated by Django 4.2.8 on 2023-12-31 00:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallBackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('requested_date_of_call', models.DateField(auto_now=True)),
                ('time_of_day', models.CharField(blank=True, max_length=255, null=True)),
                ('call_asap', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirm_text', models.BooleanField(default=False)),
                ('services_of_interest', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical', models.CharField(max_length=255)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('customers_chemicals', models.BooleanField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('services_of_interest', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_sent', models.DateField(blank=True, null=True)),
                ('time_of_day', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_confirm_text', models.BooleanField(default=False)),
                ('picture_1', models.ImageField(blank=True, default='estimate_images/image.jpg', upload_to='estimate_images/')),
                ('picture_2', models.ImageField(blank=True, default='estimate_images/image.jpg', upload_to='estimate_images/')),
                ('picture_3', models.ImageField(blank=True, default='estimate_images/image.jpg', upload_to='estimate_images/')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('has_drivers_license', models.BooleanField(blank=True, null=True)),
                ('has_vehicle', models.BooleanField(blank=True, null=True)),
                ('vehicle_has_hitch', models.BooleanField(blank=True, null=True)),
                ('desired_responsibilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None)),
                ('has_general_experience', models.BooleanField(blank=True, null=True)),
                ('has_pro_experience', models.BooleanField(blank=True, null=True)),
                ('years_of_experience', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Install',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.service')),
                ('description', models.TextField()),
            ],
            bases=('forms.service',),
        ),
        migrations.CreateModel(
            name='Remodel',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.service')),
                ('description', models.TextField()),
            ],
            bases=('forms.service',),
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.service')),
                ('description', models.TextField()),
            ],
            bases=('forms.service',),
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.service')),
                ('description', models.TextField()),
            ],
            bases=('forms.service',),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('date_performed', models.DateField(blank=True, null=True)),
                ('before_picture', models.ImageField(blank=True, default='maintenance/image.jpg', upload_to='maintenance/')),
                ('after_picture', models.ImageField(blank=True, default='maintenance/image.jpg', upload_to='maintenance/')),
                ('weather_delay', models.BooleanField(default=False)),
                ('chemical_consumption', models.ManyToManyField(blank=True, to='forms.chemicalconsumption')),
                ('optional_additions', models.ManyToManyField(blank=True, to='forms.maintenanceextras')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.IntegerField(blank=True, null=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('qb_invoice_number', models.CharField(blank=True, null=True)),
                ('date_of_service', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('received_by', models.CharField(blank=True, max_length=255, null=True)),
                ('service_list', models.ManyToManyField(to='forms.service')),
            ],
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('services_of_interest', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('user_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('urgency', models.CharField(blank=True, max_length=255, null=True)),
                ('appt_flexibility', models.CharField(blank=True, max_length=255, null=True)),
                ('someone_willB_home', models.BooleanField(default=False)),
                ('requests_a_time_of_day', models.BooleanField(default=False)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('requested_time_of_day', models.CharField(blank=True, max_length=255, null=True)),
                ('has_attached_estimate', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_date', models.DateField(blank=True, null=True)),
                ('attached_estimate', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='forms.estimate')),
            ],
        ),
    ]
