# Generated by Django 4.2.8 on 2024-01-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_bookingrequest_attached_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceAgreementForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_of_service', models.CharField(max_length=255)),
                ('insurance_understand', models.BooleanField()),
                ('equipment_comments', models.TextField()),
                ('equipment_understand', models.BooleanField()),
                ('access_comments', models.TextField()),
                ('equipment_is_good', models.BooleanField()),
                ('there_is_access', models.BooleanField()),
                ('responsibility_comments', models.TextField()),
                ('pump_settings_understand_2', models.BooleanField()),
                ('access_understand', models.BooleanField()),
                ('pump_settings_understand_1', models.BooleanField()),
                ('leak_chemical_understand', models.BooleanField()),
                ('understand_termination', models.BooleanField()),
                ('bundled_maintenance_plan', models.BooleanField()),
                ('check_payment_extra_pref', models.CharField(max_length=255)),
                ('prefered_payment_method', models.CharField(max_length=255)),
                ('end_date', models.DateField()),
                ('start_date', models.DateField()),
                ('alternate_service_day_preference', models.CharField(max_length=255)),
                ('weather_delay_preference', models.CharField(max_length=255)),
                ('communication_comments', models.TextField()),
                ('preferred_communication_method', models.CharField(max_length=255)),
                ('select_extras', models.CharField(max_length=255)),
                ('select_scope', models.CharField(max_length=255)),
            ],
        ),
    ]
