# Generated by Django 4.2.8 on 2024-01-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_maintenanceagreementform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='install',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repair',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
