# Generated by Django 4.2.8 on 2024-01-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_install_description_alter_remodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceagreementform',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceagreementform',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
