# Generated by Django 4.2.8 on 2024-01-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_maintenanceagreementform_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingrequest',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='bookingrequest',
            old_name='user_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='callbackrequest',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='callbackrequest',
            old_name='user_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='estimate',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='recruitform',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='estimate',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recruitform',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
