# Generated by Django 4.2.8 on 2024-01-11 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0006_rename_customer_email_bookingrequest_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="customer_email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="maintenance",
            old_name="customer_email",
            new_name="email",
        ),
    ]
