# Use an official Node runtime as a parent image
FROM node:19

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the entire project to the working directory
COPY . .


# Expose the port the app runs on
EXPOSE 3000

# Define the command to run the application
CMD [ "yarn", "dev", "--host" ]
