# Generated by Django 4.2.8 on 2023-12-31 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(default='default')),
                ('picture_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('picture_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('picture_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('picture_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_chemical', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductWrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('ordered', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=1)),
                ('paid', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('date_delivered', models.DateField(blank=True, null=True)),
                ('date_purchased', models.DateField(blank=True, null=True)),
                ('requested_speed', models.CharField()),
                ('payment_method', models.CharField()),
                ('delivery_type', models.CharField()),
                ('returned', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_list', models.ManyToManyField(blank=True, to='store.productwrapper')),
            ],
        ),
    ]
